### ISSUE TITLE
Fast jeder Testfall schlägt fehl

### ISSUE THREAD

**Issue by OrdenKrieger** [punkIRC/punkIRC-test#33]
Seit version 1.2.1, egal welches Format die RPL_WELCOME, RPL_YOURHOST, RPL_CREATED, RPL_MYINFO Strings haben, die Tests schlagen fehl mit:
[completeAuthAtOnce()@08:36:30]: Tried to parse an empty string!
Desweiteren scheint der Test-Client alter Strings im Puffer zu behalten, so behauptet er zum Beispiel bei PONG, dass er eine Antwort erhalten hat obwohl diese im Log nie steht und auch manuell getestet nie kommt. Ich denke hier bleiben die Strings von Registration im Puffer welcher als Antwort auf interpretiert. Außerdem fehlt hier ein Leerzeichen zwischen server_response und 'Closing Link' https://github.com/punkIRC/punkIRC-test/blob/master/src/main/antlr/de.rubenmaurer.punk/IRC.g4#L141
Des Weiteren wäre eine Beispiel Liste von Formaten, die der Test Client akzeptiert, schön. Am besten für mögliches alle RPLs und ERRs. Ich konnte in der neusten Version fast gar keinen Test passen und die alte Version war da auch nicht sehr aufschlussreich.

**Comment by Schrotty** [comment]
Zu der Fehlermeldung: Beim Client kommt keine Rückmeldung vom Server an und deswegen schlägt der Test fehl. Das Format ist erstmal zweitrangig in dem Fall.
Zum Puffer: Wird ein Kommando abgesetzt, wird das interne Log überschrieben um eben solche Fehler zu vermeiden.
Zur Grammatik: Das Leerzeichen findet sich weiter oben unter 'server_response_error'
Die Formate die vom Server akzeptiert werden, decken sich mit dem was im RFC steht und kann ansonsten auch in der Grammatik nachgelesen werden.

**Comment by OrdenKrieger** [comment]
Er bekommt aber antworten.
https://hastebin.com/jiciqijaqu.cs

Und bei Pong kommt nichts an:
https://hastebin.com/kihozomaba.rb

**Comment by IZEDx** [comment]
Shameless self promotion lol: https://codebin.ized.io/

**Comment by milanico2309** [comment]
Ich habe das selbe Problem, denke ich... Tests die in alten Versionen funktionierten schlagen nun fehl.
![unknown1](https://user-images.githubusercontent.com/34548427/69508549-7abbcc80-0f36-11ea-888a-70300c890098.png)
![unknown2](https://user-images.githubusercontent.com/34548427/69508571-87d8bb80-0f36-11ea-94fc-122cef99f297.png)

Logs:

[2019-11-25 03:21:55]  DEBUG  SEND: USER elisabeth * * :Chloe Elisabeth Price
[2019-11-25 03:21:58]  DEBUG  SEND: NICK chloe
[2019-11-25 03:21:58]  DEBUG  RECV: :chloe 101 Milan-PC :Welcome to the Internet Relay Network chloe!elisabeth@Milan-PC
[completeAuthAtOnce()@03:21:58]: Tried to parse an empty string!

[2019-11-25 03:22:03]  DEBUG  SEND: USER maxine * * :Maxine Caulfield
[2019-11-25 03:22:06]  DEBUG  SEND: NICK max
[2019-11-25 03:22:06]  DEBUG  RECV: :max 101 Milan-PC :Welcome to the Internet Relay Network max!maxine@Milan-PC
[nickUserParsing1()@03:22:06]: Tried to parse an empty string!

**Comment by Schrotty** [comment]
Der Client hat in den Versionen =< 1.2.0 leere Strings fälschlicherweise akzeptiert und den Test grün laufen lassen.
Besagtes Verhalten wurde in v1.2.1 gefixt und wenn jetzt die Fehlermeldungen 'Tried to parse an empty string!' auftaucht, dann mit hoher Wahrscheinlichkeit weil in den Responses der Statuscode fehlt. Ohne den werden eingehende Nachrichten nicht im entsprechenden Log abgelegt.

Das Verhalten ist somit korrekt, lediglich die Fehlermeldungen sind noch zu vage formuliert. Dazu siehe #35
